version: "3.8"
services:
  leaderboard_service:
    ports:
      - "8080:8080"
    build:
      context: ./leaderboard_service
      dockerfile: Dockerfile

    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=OTTER
      - DB_NAME=your_database
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=OTTER
      - POSTGRES_DB=your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d your_database"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
