version: "3.8"
services:
  leaderboard_service:
    ports:
      - "8080:8080"
    build:
      context: ./leaderboard_service
      dockerfile: Dockerfile

    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      postgres:
        condition: service_healthy

  game_service:
      build:
        context: ./game_service
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      depends_on:
        - postgres

  postgres:
    image: postgres:latest
    env_file:
      - base.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  client_application:
    build:
      context: ./client_application
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - leaderboard_service
