// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Leaderboard struct {
	UserID   string `json:"user_id"`
	UserName string `json:"user_name"`
	Rank     int32  `json:"rank"`
	Score    int32  `json:"score"`
}

type LeaderboardResponse struct {
	Data    []*Leaderboard `json:"data"`
	Metrics *QueryMetrics  `json:"metrics"`
}

type Mutation struct {
}

type Query struct {
}

type QueryMetrics struct {
	QueryTime   float64 `json:"queryTime"`
	RecordCount int32   `json:"recordCount"`
	DataSource  string  `json:"dataSource"`
}
